// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRmS8v_-2W6i2_C5UDPJl81yqUbr3RJlY',
    appId: '1:1050751488222:web:a10f00670a5fbd80bdb24f',
    messagingSenderId: '1050751488222',
    projectId: 'todoapp-68338',
    authDomain: 'todoapp-68338.firebaseapp.com',
    storageBucket: 'todoapp-68338.appspot.com',
    measurementId: 'G-1KM2TDTXRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv6cBeoOblTwVDkAJxfawZJur3WGC0k6M',
    appId: '1:1050751488222:android:1a19b46dc1778dd7bdb24f',
    messagingSenderId: '1050751488222',
    projectId: 'todoapp-68338',
    storageBucket: 'todoapp-68338.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrOBKUU_0Kh0f46fl5KlREicBKJxKGjcU',
    appId: '1:1050751488222:ios:72a3d2680e12d90dbdb24f',
    messagingSenderId: '1050751488222',
    projectId: 'todoapp-68338',
    storageBucket: 'todoapp-68338.appspot.com',
    androidClientId: '1050751488222-hsi0tcrh7636r3ahnk22sj9m4714grlb.apps.googleusercontent.com',
    iosClientId: '1050751488222-9mhg9vc9lf3dkac9mj6350ljo8kisiiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.lysts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrOBKUU_0Kh0f46fl5KlREicBKJxKGjcU',
    appId: '1:1050751488222:ios:72a3d2680e12d90dbdb24f',
    messagingSenderId: '1050751488222',
    projectId: 'todoapp-68338',
    storageBucket: 'todoapp-68338.appspot.com',
    androidClientId: '1050751488222-hsi0tcrh7636r3ahnk22sj9m4714grlb.apps.googleusercontent.com',
    iosClientId: '1050751488222-9mhg9vc9lf3dkac9mj6350ljo8kisiiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.lysts',
  );
}
